### ISSUE TITLE
Formatting for forms

### ISSUE THREAD

**Issue by sb5346** [fac22/Sunny_North_London_Agency#13]
I think we should look at the format style of the forms. I did not change it much from my own pages when I added it here but now the fields look odd.

**Comment by jijip41** [comment]
looks better now but needs some improvement. 
if you think it's priority, we can work on this afterwards :)

**Comment by sb5346** [comment]
Hello Ji, I like the grid for the profiles and it seems to remain "responsive" but the forms side by side work less well. Can we have them one on top of the other? Then would not have to scroll across for the second form.
I did not add a secondary check for one of my functions, so I can change the layout when I do this.
Please check and let me know.

**Comment by jijip41** [comment]
Hi Saira did you mean change flex-direction to column? Yes I can do that!
(I used grid for about team and flexbox for the forms)

**Comment by sb5346** [comment]
Yes, because the rest looks good but on narrower screen the forms have to be scrolled across.
Let me know when you work on it as I need to update my form to prevent it from submitting.

**Comment by jijip41** [comment]
Done!

**Comment by sb5346** [comment]
Did you publish already? Is it on live page?
