### ISSUE TITLE
scroll to each section

### ISSUE THREAD

**Issue by jijip41** [fac22/Sunny_North_London_Agency#15]
I wanted to do this but I'm running out time :(
Hopefully I can start doing it tomorrow

**Comment by sb5346** [comment]
Hello Ji, I'm not sure which you mean. Do you mean horizontal scrolling?
By the way, the navigation links don't link to anything. I can raise it separately or change them myself. But as you worked on this, I did not want to change it before checking with you.

**Comment by jijip41** [comment]
Morning Saira, Yes the navigation links' references are all '#' at the moment so it doesn't link to anything. 
What I meant was when we click the links, the screen will be scrolled to each section. Does it make sense? 
What do you think? If you had another thoughts happy to talk about it!

**Comment by sb5346** [comment]
Yes! That's perfect :) I think in the beginning it's fine because we don't have much content but now we have a little bit of content so will work better.
I didn't think you would check so early - sorry to disturb you in the morning.
