### ISSUE TITLE
Add new team member form

### ISSUE THREAD

**Issue by sb5346** [fac22/Sunny_North_London_Agency#7]
Hello Ji, can you please add function for:

As a member of agency, I want to:

- Input the name, an image of, and description of the new team member (E1)
- Input an admin password and see if this has been accepted or rejected (E1)
- Be notified if the email address doesn’t look right (E2)
- Be notified if the description I’m writing is too long (E2)
- See the new member on the page once I click a button (E3)

**Comment by sb5346** [comment]
By the way Ji, could you add a heading for your form? So it will distinguish from content above. I added a h3 for mine.
I know you mentioned making a grid for the about section. 
Thanks :)

**Comment by jijip41** [comment]
added all functions:)
